language: node_js
node_js:
  - 13
dist: trusty
sudo: false

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn test

deploy:
  # Deploy to Server
  provider: script
  script: openssl aes-256-cbc -K $encrypted_2c5959d3eced_key -iv $encrypted_2c5959d3eced_iv -in scripts/alias.pem.enc -out alias.pem -d && chmod 400 alias.pem && ssh -oStrictHostKeyChecking=no -i alias.pem $SERVER_URL "./deploy.sh"
  on:
    tags: true
